### ISSUE TITLE
PATWEAKS.DAT issue with track count

### ISSUE THREAD

**Issue by seouljah760** [lanmarc77/playaway#1]
I have a dozen or so Playaways, currently awaiting some pogo pins to connect to these without opening all of them up and soldering a USB cable. I did open one HD + LIGHT (with the larger display) and did the following:

- copied entire hynix storage to local backup
- deleted all existing .awb files on the player
- changed the PATWEAKS.DAT "NMD093" portion to "NMD003"
-- Full PATWEAKS.DAT string: AWBVOL072002SLD090080PUP003**TRKNMD093**BLN020BLP020COP5522~ minus the copywrite text.
- Converted 3 wav files with the encode.exe
- named them 0001 my audiobook 0000, 0002 my audiobook 0000, 0003 my audiobook 0000
- uploaded them to the Playaway
- Playaway says something like "incorrect number of files" on screen (error 4 I believe)
- changed back to NMD093
- It now only  plays ~1:45 of ~15:00 minutes of the 2nd track with no ability to change tracks 

Stuck on what else to try, I've reconverted the files, no luck with playing or changing tracks 1 & 3.
I did open up the playqueue.dat in a hex editor and the first hex is 5D (93 decimal) and it's the same amount of tracks and same number as the NMD093. Does yours have the same issue on the larger screen one? can you post what your payqueue.dat has in it?
![Screenshot 2023-12-28 193059](https://github.com/lanmarc77/playaway/assets/20866956/c8d6c31a-67cd-4ed4-b1cd-5a5db66ec5fe)
I dropped a screenshot of my hex editor of the playqueue.dat to show you what i'm talking about. As changing the NMD number doesn't seem to do anything as far as I can tell... Maybe the NMD and hex value in the playqueue.dat needs to match on the larger screen version? Also the PATWEAKS.DAT doesn't have any track length hex numbers in mine, but does have TRK right before NMD093, which I didn't see in your example.

**Comment by lanmarc77** [comment]
Hi, just shortly a bit longer later.
Delete ALL files and folders from the Playaway. Only PATWEAKS.DAT and the .awb files need to be on the player. The other files are recreated and partly contain the number of tracks as well. So I guess we have a caching issue now.
I have not yet analysed all my PATWEAKS.DAT but I have not yet seen a TRK flag. Thats something new cool!
In the PATWEAKS.DAT you actually only need it to be filled until and including NMD flag. Everything else you can remove. As we do not know what TRK does I suggest removing this flag as well. 
So it should look like: AWBVOL072002SLD090080PUP003NMD003

Let me know how it went, I am back from dreaming land in about 12hrs.

**Comment by seouljah760** [comment]
That seemed to fix it. I only changed the NMD number and deleted all but the PATWEAKS.DAT. Re-uploaded the .awb files I made and it's playing all three files now. Thank you for the guidance!

**Comment by lanmarc77** [comment]
Great to hear. I will most likely restructure that chapter about the PATWEAKS.DAT and then add the information with the other files and that they should be removed.
Meanwhile I added TRK to one of my Playaways and the difference is that it now shows Track instead of Chapter when skipping. So one can choose.

**Comment by lanmarc77** [comment]
Just figured out that only NMDXXX is needed in PATWEAKS.DAT and change the documentation accordingly.
If you find the time I would appreciate if you add your models to the Models overview. It is a bit of work though.

**Comment by seouljah760** [comment]
I can add mine, no worries.

**Comment by seouljah760** [comment]
So some new developments since December. I was gone most of January, and just now getting back into hobby stuff. I gave a couple to my friend to see if swapping out TSOP flash for larger ones would work, TBD... BUT, I got my hands on 3 new ones, and these version 7s have a totally different ARM chip. You can't even access the audio files, there's just a blank drive when you pogo the pads. The flash themselves are 8GB/64Gb, with only about 200MB of storage visable. The chip inside is a ATJ2157 220MHz ARM Cortex-M4F. If you know a way to access the hidden part of the flash, that'd be helpful.

I did find out a few things from a librarian that has seen multiple versions of the same books and dealt with Playaway distributors. It appears that correlating book titles with internal specs is pointless. The distributors just carry tons of Playaway blanks, in various versions/sizes. When orders come in, they just load up the files from a repo. Depending on the size/length of audiobook, they just grab a blank from a stack with the correct size flash. They then grab a blank orange plastic cover and print the book's back sticker and cover insert as they go. They do not mass produce specific books. So you can get the same book with wildly different internal specs.

**Comment by lanmarc77** [comment]
Very interesting news detective. :-)

To flash change:
My guess is this could work if the firmware versions of source and target player are compatible. Not really knowing what exactly this means. But the flash is structured/partitioned as described in the STMP SDK. I do not know how much of these structures differ from version to version.
If you swap the chip out for a brand new one you will either need to create an own partition table or make a copy from the old chip and adjust accordingly.

To new model:
I am unsure how you mean "new". It could mean you just acquired them or it could mean these are the newest=youngest model types of Playaways. As you mentioned a segment display I will assume it is an old model because all the new ones I have seen so far have graphics displays. There was in fact a first model type. According to Wikipedia this older model did not support "HD Audio" (whatever this marketing term means). Judging from pictures these older models did not contain the marking "HD Audio" and the stickers are placed differently. Needing to use a different file encoding for these old models could also explain the bigger flash chips. They could just not use a more modern compression algorithm. Pictures please! From inside and out.
According to wikipedia Actions (the company of the ATJ2157) was sued by Sigmatel (now Freescale) for infringement. It can very well be that this case made Playaway switch to Sigmatel.
I could not really find a datasheet of the processor you described but if it does register as mass storage device then there is most likely firmware on it that implements this service. You should check how the partition table of the mass storage device looks. Maybe there are hidden partitions or partitions without a specific file system type. If possible dump the whole mass storage device so we can have a look. Also possible might be that a specific USB command must be send for other USB configurations to be activated. You could try sending an eject that is meant for CD-drives.
And check if you have enabled displaying hidden files in the OS you use. Might be that the files have the hidden flag set.

To distribution process:
So my thesis served its purpose. At least to be there to be challenged. I do not like the big table in the documentation anyways and will think on how to build that device database a bit differently.
Can you figure out if the local distributors only upload the audio files in a way we do or if they also flash the initial firmware on the devices? If you are able to get pictures from their equipment that would be great.
In Germany these players are almost not used so no one knows anything.

A nice hobby indeed.
